### ISSUE TITLE
NPE in AbstractBayesianClassifier

### ISSUE THREAD

**Issue by alikashmar** [AbeelLab/javaml#2]
The Classname2IndexCCountermap uses the String value of the class as a key but when querying the map, the actual class is used. 

Putting into the map:

```
for (Object o : trainingData.classes()) {
    String classname = o.toString();
    Classname2IndexCCountermap.put(classname, cnt);
    classes[cnt] = classname;
    cnt++;
}
```

Getting from the map:

```
for (Instance inst : Instances2Train) {
    classFrequencies[Classname2IndexCCountermap.get(inst.classValue())]++;
}
```

This would only work if the classValue is of type String.

**Comment by thomasabeel** [comment]
In practice the classValue is indeed often a String, so this problem has gone unnoticed.

I also noticed there are many cases where this map is queried using get(inst.classValue()), so changing that is not really an option.

Would removing " String classname = o.toString();" be a viable solution and put straight objects in the map. This implicitly requires proper hash and equals functions to be implemented on the class label object, but it should work in more cases than the current version.

**Comment by alikashmar** [comment]
For scenarios where the class is binary i.e. 0 or 1, it would be a problem. I suggest using the object  as the key. When dealing with maps, your keys usually have to implement the equals/hashcode methods anyways, if they're not implemented already.
