### ISSUE TITLE
MCL Code License

### ISSUE THREAD

**Issue by dustalov** [AbeelLab/javaml#4]
Hello,

I would like to use the implementation of the MCL algorithm from Java-ML in my graph clustering software. As I currently read, Java-ML is licensed under GPL, while my code is Apache-licensed.

May I ask you for the permission to use the MCL implementation from java-ml as a dependency for my library <https://github.com/dustalov/watset-java> under the Apache license?

**Comment by thomasabeel** [comment]
I do not own full copyright on that code, please retrieve the implementation from the original author: http://www.arbylon.net/resources.html
